// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lQsn1OkGt4q2asqMcwN8WqkkuQuxXA4',
    appId: '1:631993230849:web:23ffcc204c6e8527cdc200',
    messagingSenderId: '631993230849',
    projectId: 'electionapp-d3bc3',
    authDomain: 'electionapp-d3bc3.firebaseapp.com',
    storageBucket: 'electionapp-d3bc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3MQm8faeJ8veJa1OI_sBTD9cvHGODQlw',
    appId: '1:631993230849:android:219c7b0a967b331ccdc200',
    messagingSenderId: '631993230849',
    projectId: 'electionapp-d3bc3',
    storageBucket: 'electionapp-d3bc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNCq71ECOlARO73WmFtwrV0iwWlqqUWE',
    appId: '1:631993230849:ios:f83256c22f6fc9d7cdc200',
    messagingSenderId: '631993230849',
    projectId: 'electionapp-d3bc3',
    storageBucket: 'electionapp-d3bc3.appspot.com',
    iosBundleId: 'com.example.eElection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNCq71ECOlARO73WmFtwrV0iwWlqqUWE',
    appId: '1:631993230849:ios:f83256c22f6fc9d7cdc200',
    messagingSenderId: '631993230849',
    projectId: 'electionapp-d3bc3',
    storageBucket: 'electionapp-d3bc3.appspot.com',
    iosBundleId: 'com.example.eElection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9lQsn1OkGt4q2asqMcwN8WqkkuQuxXA4',
    appId: '1:631993230849:web:8850b5e3fb2249c0cdc200',
    messagingSenderId: '631993230849',
    projectId: 'electionapp-d3bc3',
    authDomain: 'electionapp-d3bc3.firebaseapp.com',
    storageBucket: 'electionapp-d3bc3.appspot.com',
  );
}
